/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as SetupStepRouteImport } from './routes/setup.$step'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDomainSplatRouteImport } from './routes/api/domain/$'
import { Route as LibrariesLibraryIdEventsEventIdPhotosPhotoIdRouteImport } from './routes/libraries.$libraryId.events.$eventId.photos.$photoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupStepRoute = SetupStepRouteImport.update({
  id: '/setup/$step',
  path: '/setup/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainSplatRoute = ApiDomainSplatRouteImport.update({
  id: '/api/domain/$',
  path: '/api/domain/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesLibraryIdEventsEventIdPhotosPhotoIdRoute =
  LibrariesLibraryIdEventsEventIdPhotosPhotoIdRouteImport.update({
    id: '/libraries/$libraryId/events/$eventId/photos/$photoId',
    path: '/libraries/$libraryId/events/$eventId/photos/$photoId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/setup/$step': typeof SetupStepRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/domain/$': typeof ApiDomainSplatRoute
  '/libraries/$libraryId/events/$eventId/photos/$photoId': typeof LibrariesLibraryIdEventsEventIdPhotosPhotoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/setup/$step': typeof SetupStepRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/domain/$': typeof ApiDomainSplatRoute
  '/libraries/$libraryId/events/$eventId/photos/$photoId': typeof LibrariesLibraryIdEventsEventIdPhotosPhotoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/setup/$step': typeof SetupStepRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/domain/$': typeof ApiDomainSplatRoute
  '/libraries/$libraryId/events/$eventId/photos/$photoId': typeof LibrariesLibraryIdEventsEventIdPhotosPhotoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/api/openapi.json'
    | '/setup/$step'
    | '/api/auth/$'
    | '/api/domain/$'
    | '/libraries/$libraryId/events/$eventId/photos/$photoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/api/openapi.json'
    | '/setup/$step'
    | '/api/auth/$'
    | '/api/domain/$'
    | '/libraries/$libraryId/events/$eventId/photos/$photoId'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/api/openapi.json'
    | '/setup/$step'
    | '/api/auth/$'
    | '/api/domain/$'
    | '/libraries/$libraryId/events/$eventId/photos/$photoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  SetupStepRoute: typeof SetupStepRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDomainSplatRoute: typeof ApiDomainSplatRoute
  LibrariesLibraryIdEventsEventIdPhotosPhotoIdRoute: typeof LibrariesLibraryIdEventsEventIdPhotosPhotoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/$step': {
      id: '/setup/$step'
      path: '/setup/$step'
      fullPath: '/setup/$step'
      preLoaderRoute: typeof SetupStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domain/$': {
      id: '/api/domain/$'
      path: '/api/domain/$'
      fullPath: '/api/domain/$'
      preLoaderRoute: typeof ApiDomainSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId/events/$eventId/photos/$photoId': {
      id: '/libraries/$libraryId/events/$eventId/photos/$photoId'
      path: '/libraries/$libraryId/events/$eventId/photos/$photoId'
      fullPath: '/libraries/$libraryId/events/$eventId/photos/$photoId'
      preLoaderRoute: typeof LibrariesLibraryIdEventsEventIdPhotosPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  SetupStepRoute: SetupStepRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDomainSplatRoute: ApiDomainSplatRoute,
  LibrariesLibraryIdEventsEventIdPhotosPhotoIdRoute:
    LibrariesLibraryIdEventsEventIdPhotosPhotoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
